version: '3'
services:
  db:
    platform: linux/x86_64
    image: mysql:8
    environment:
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQL_ROOT_PASSWORD: myrootpassword
      TZ: Asia/Tokyo
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_general_ci','--default-time-zone=+09:00']
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3306:3306"
